spring:
  application:
    name: order

  profiles:
    active: dev

  cloud:
    nacos:
      config:
        enabled: true
        file-extension: yml
        prefix: ${spring.application.name}-application
        namespace: ${spring.profiles.active}
      discovery:
        enabled: true
        namespace: ${spring.profiles.active}

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/auth?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root

rocketmq:
  producer:
    name-server-addr: 127.0.0.1:9876
    group: order-group
    topic: order
    order-create-tag: order-create-tag
    order-pay-tag: order-pay-tag
    order-refund-tag: order-refund-tag

  consumer:
    name-server-addr: 127.0.0.1:9876
    group: order-group
    topic: order
    order-create-tag: order-create-tag
    order-pay-tag: order-pay-tag
    order-refund-tag: order-refund-tag

wx:
  pay:
    mchId:
    mchKey:
    subAppId:
    subMchId:
    keyPath:
    privateKeyPath:
    privateCertPath:
    apiV3Key:
    certSerialNo:
    sandboxEnabled:
    payNotifyUrl:
    refundNotifyUrl:

