server:
  port: 9000

spring:
  application:
    name: gateway

  profiles:
    active: dev

  cloud:
    nacos:
      config:
        enabled: true
        file-extension: yml
        prefix: ${spring.application.name}-application
        namespace: ${spring.profiles.active}
      discovery:
        enabled: true
        namespace: ${spring.profiles.active}

    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true

      routes:
        - id: 认证中心服务
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: '系统服务'
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: '会员服务'
          uri: lb://member
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1

  redis:
    database: 1
    host: 127.0.0.1
    port: 6379

  main:
    allow-bean-definition-overriding: true

security:
  enabled: true
  refreshTokenUrl: "http://localhost:9001/oauth/refreshToken?accessToken="

  ignoreUrls:
    # Knife4j
    - /webjars/**
    - /doc.html
    - /swagger-resources/**
    - /*/v2/api-docs

    # oauth2
    - /auth/oauth/**
    - /admin/sms/**




