server:
  port: 9000

spring:
  application:
    name: gateway

  profiles:
    active: dev

  cloud:
    nacos:
      config:
        enabled: true
        file-extension: yml
        prefix: ${spring.application.name}-application
        namespace: ${spring.profiles.active}
      discovery:
        enabled: true
        namespace: ${spring.profiles.active}

    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true

      routes:
        - id: 认证中心服务
          uri: lb://auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: '系统服务'
          uri: lb://admin
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: '会员服务'
          uri: lb://member
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1


  main:
    allow-bean-definition-overriding: true
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379

security:
  enabled: true
  refreshTokenUrl: "http://localhost:9001/oauth/refreshToken?accessToken="

  ignoreUrls:
    # Knife4j
    - /webjars/**
    - /doc.html
    - /swagger-resources/**
    - /*/v3/api-docs
    - /favicon.ico

    # oauth2
    - /auth/oauth2/**
    - /admin/sms/**

knife4j:
  # 聚合swagger文档
  gateway:
    enable: true
    routes:
#      - name: 认证服务
#        # OpenAPI数据源，不管是Swagger/OAS3，提供地址即可聚合
#        url: /auth/v3/api-docs?group=系统服务
#        service-name: auth
#        order: 2
      - name: 系统服务
        url: /admin/v3/api-docs?group=系统服务
        service-name: admin
        order: 3
      - name: 会员服务
        url: /member/v3/api-docs?group=会员服务
        service-name: member
        order: 4





