server:
  port: 9001

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: auth

  profiles:
    active: dev

  cloud:
    nacos:
      config:
        enabled: true
        file-extension: yml
        prefix: ${spring.application.name}-application
        namespace: ${spring.profiles.active}
      discovery:
        enabled: true
        namespace: ${spring.profiles.active}


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mall-test?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root

  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

wechat:
  appId: 
  secret: 

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    show-extensions: true
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: '认证服务'
      paths-to-match: '/**'
  default-flat-param-object: false