server:
  port: 9005
spring:
  application:
    name: payment

  profiles:
    active: dev

#  cloud:
#    nacos:
#      config:
#        enabled: true
#        file-extension: yml
#        prefix: ${spring.application.name}-application
#        namespace: ${spring.profiles.active}
#      discovery:
#        enabled: true
#        namespace: ${spring.profiles.active}

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/payment?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379




